language: node_js
node_js:
  - "8.11"

notifications:
  email: false

before_script:
  - npm install --only=dev

script:
  - npm run build
  - npm run build-dist
  - npm run lint
  - npm run test
  - npm run coverage
  - npm run docs
